logging:
  level:
    org.springframework.core.env: warn
    org.springframework.jndi: warn

server:
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048

spring:
  jackson:
    serialization:
     write-dates-as-timestamps: false

initializr:
  env:
    boms:
      livelessons-bom:
        groupId: livelessons
        artifactId: livelessons-extending-dependencies
        version: 1.0.0-SNAPSHOT
    gradle:
      dependency-management-plugin-version: 0.6.0.RELEASE
  dependencies:
    - name: LiveLessons
      content:
        - name: LiveLessons Auto-configure
          id: extension
          weight: 100
          groupId: livelessons
          artifactId: livelessons-extending-autoconfigure
          description: LiveLessons auto-configuration
          bom: livelessons-bom
          starter: false
    - name: Core
      content:
        - name: Security
          id: security
          description: Secure your application via spring-security
          weight: 100
        - name: AOP
          id: aop
          description: Aspect-oriented programming including spring-aop and AspectJ
        - name: Cache
          id: cache
          description: Spring's Cache abstraction
          versionRange: 1.3.0.M1
        - name: DevTools
          id: devtools
          groupId: org.springframework.boot
          artifactId: spring-boot-devtools
          description: Spring Boot Development Tools
          versionRange: 1.3.0.M1
          starter: false
        - name: Validation
          id: validation
          description: JSR-303 validation infrastructure (already included with web)
          versionRange: 1.3.0.M1
        - name: Session
          id: session
          groupId: org.springframework.session
          artifactId: spring-session
          description: API and implementations for managing a user’s session information
          versionRange: 1.3.0.M2
          starter: false
        - name: Lombok
          id: lombok
          groupId: org.projectlombok
          artifactId: lombok
          description: Java annotation library which helps to reduce boilerplate code and code faster
          mappings:
            - versionRange: "[1.2.0.RELEASE,1.4.0.M1)"
              version: 1.16.6
          starter: false
    - name: Web
      content:
        - name: Web
          id: web
          description: Full-stack web development with Tomcat and Spring MVC
          weight: 100
          facets:
            - web
        - name: Websocket
          id: websocket
          description: Websocket development with SockJS and STOMP
        - name: HATEOAS
          id: hateoas
          description: HATEOAS-based RESTful services
          versionRange: 1.2.2.RELEASE
        - name: Rest Repositories HAL Browser
          id: data-rest-hal
          description: Browsing Spring Data REST repositories in your browser
          groupId: org.springframework.data
          artifactId: spring-data-rest-hal-browser
          versionRange: 1.3.0.M1
          starter: false
        - name: REST Docs
          id: restdocs
          description: Document RESTful services by combining hand-written and auto-generated documentation
          groupId: org.springframework.restdocs
          artifactId: spring-restdocs-mockmvc
          mappings:
            - versionRange: "[1.2.0.RELEASE,1.3.0.RC1)"
              version: 1.0.1.RELEASE
          scope: test
    - name: Ops
      content:
        - name: Actuator
          id: actuator
          description: Production ready features to help you monitor and manage your application
        - name: Actuator Docs
          id: actuator-docs
          description: API documentation for the Actuator endpoints
          versionRange: 1.3.0.M4
          groupId: org.springframework.boot
          artifactId: spring-boot-actuator-docs
        - name: Remote Shell
          id: remote-shell
          description: CRaSH shell integration
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: starter.zip
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      sts-id: gradle.zip
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
    - name: Gradle Config
      id: gradle-build
      description: Generate a Gradle build file
      sts-id: build.gradle
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 1.8
      default: true
    - id: 1.7
      default: false
    - id: 1.6
      default: false
  languages:
    - name: Java
      id: java
      default: true
  bootVersions:
    - name: 1.4.1
      id: 1.4.1.RELEASE
      default: true
